[k3s_master]
dulc3-os  ansible_host=10.0.0.2  ansible_user=dulc3

[k3s_workers]
# Add standard worker nodes here

[laptop_nodes]
dulc3-top  ansible_host=10.0.0.4  ansible_user=dulc3

[all:vars]
ansible_python_interpreter=/usr/bin/python3
