version: '3.8'

services:
  backend:
    build:
      context: ./backe_end
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - webnet
      - ollama-n8n-network  # 👈 so it can talk to Ollama
    restart: unless-stopped

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - "8089"
    networks:
      - webnet
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - webnet
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_FLASH_ATTENTION=1
    networks:
      - ollama-n8n-network
    tty: true
    restart: unless-stopped

networks:
  webnet:
    driver: bridge
  ollama-n8n-network:
    driver: bridge

volumes:
  ollama:
