'use client'

import { useQuery } from '@tanstack/react-query'
import { notebooksApi } from '@/lib/api/notebooks'

interface CachedSuggestions {
  count: number
  questions: string[]
}

// Suggested questions are generated by an LLM (GPU-costly on this stack), so —
// like the autoname guard — they're cached in localStorage keyed by notebook id
// and only regenerated when the notebook's source count GROWS. staleTime is
// Infinity: within a session the react-query cache (keyed on count) holds them.
function lsKey(notebookId: string) {
  return `onb:suggestq:${notebookId}`
}

function readCache(notebookId: string): CachedSuggestions | null {
  if (typeof window === 'undefined') return null
  try {
    const raw = window.localStorage.getItem(lsKey(notebookId))
    if (!raw) return null
    const parsed = JSON.parse(raw) as CachedSuggestions
    if (Array.isArray(parsed.questions) && typeof parsed.count === 'number') return parsed
  } catch {
    /* corrupt cache → regenerate */
  }
  return null
}

function writeCache(notebookId: string, value: CachedSuggestions) {
  if (typeof window === 'undefined') return
  try {
    window.localStorage.setItem(lsKey(notebookId), JSON.stringify(value))
  } catch {
    /* ignore quota errors */
  }
}

/**
 * NotebookLM-style suggested questions for the notebook chat's empty state.
 * Fetches once per (notebook, source count) and persists across reloads.
 * `enabled` should be false while the chat already has messages — the chips
 * only render on the empty state, so don't burn an LLM call for nothing.
 */
export function useSuggestedQuestions(
  notebookId: string,
  sourceCount: number,
  enabled: boolean,
) {
  return useQuery<string[]>({
    queryKey: ['onb-suggested-questions', notebookId, sourceCount],
    enabled: enabled && !!notebookId && sourceCount > 0,
    staleTime: Infinity,
    retry: false,
    queryFn: async () => {
      const cached = readCache(notebookId)
      // Reuse the stored set until the source count grows (or shrinks to it).
      if (cached && cached.count >= sourceCount && cached.questions.length > 0) {
        return cached.questions
      }
      const res = await notebooksApi.suggestQuestions(notebookId)
      const questions = (res?.questions ?? []).filter((q) => typeof q === 'string' && q.trim())
      if (questions.length > 0) writeCache(notebookId, { count: sourceCount, questions })
      return questions
    },
  })
}
